[project]
name = "tket2-dataflow"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "hugr>=0.13.0",
    "selene-hugr-qis-compiler>=0.2.1",
    "tket>=0.12.1",
    "tket-exts>=0.10.0",
]
