use crate::bit_vector::BitVector;
use itertools::{interleave, Itertools};
use std::fmt;
use std::iter::zip;
use std::{cmp::min, fmt::Display};

#[derive(Debug, Clone)]
pub struct SymplecticTableau {
    // Total number of qubits in the system; each may represent an input, output, or intermediary point in the original circuit, but are uniformly considered outputs of the Choi-state considered here
    pub nb_qubits: usize,

    // Number of stabilizers in the tableau; we do not impose any requirements on how this compares to nb_qubits
    pub nb_stabs: usize,

    // Binary tables; since we expect to perform a lot of row multiplications, we use a StringMajor ordering - first index for string, then index into the BitVector for qubits
    pub z: Vec<BitVector>,
    pub x: Vec<BitVector>,

    // Keep signs in a single vector
    pub signs: BitVector,
}

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub enum PauliXZ {
    X,
    Z,
}

/// Given two SymplecticTableau objects L and R, their JointDecomposition identifies a linearly independent set of generators split into a few kinds.
/// First, we identify pairs of generators from each tableau which anti-commute with each other but commute with all others. After removing these, all remaining generators mutually commute.
/// We can then compute generators for the intersection - those Pauli strings generated by both L and R. When incorporating phase information, we can always make it so that at most one of these generating Pauli strings has a different phase in L and R; for all others, they exist in L and R exactly with the same phase.
/// When L and R are not complete or over the same sets of qubits, then we may need some additional generators for L that commute with R but are not generated by R, and vice versa.
pub struct JointDecomposition {
    pub tab: SymplecticTableau,
    pub n_ac_pairs: usize,
    pub just_left: usize,
    pub just_right: usize,
    pub phase_flip_term: bool,
}

impl JointDecomposition {
    pub fn ac_range(&self) -> (usize, usize) {
        (0, 2 * self.n_ac_pairs)
    }

    pub fn just_left_range(&self) -> (usize, usize) {
        let offset = 2 * self.n_ac_pairs;
        (offset, offset + self.just_left)
    }

    pub fn just_right_range(&self) -> (usize, usize) {
        let offset = 2 * self.n_ac_pairs + self.just_left;
        (offset, offset + self.just_right)
    }

    pub fn phase_flip_term_index(&self) -> Option<usize> {
        if self.phase_flip_term {
            Some(2 * self.n_ac_pairs + self.just_left + self.just_right)
        } else {
            None
        }
    }

    pub fn join_range(&self) -> (usize, usize) {
        (
            2 * self.n_ac_pairs
                + self.just_left
                + self.just_right
                + if self.phase_flip_term { 1 } else { 0 },
            self.tab.nb_stabs,
        )
    }
}

pub struct ControlledMeet {
    // The tableau whose rows are given by generators from each of the input tableaus
    // Generators of the join appear as is
    // The remaining generators for each input tableau appear with additional control values, such that post-selecting each of l/r_post_selects leaves generators for the left/right input
    // Whilst it can result in more qubits used, we restrict the post-selections to Z or X on a single control qubit for simplicity; this includes if the left and right input have generators with the same Pauli string but different phase, where it is possible to use a single row and control qubit by tracking the phase of the post-selection, but we will instead duplicate for now
    tab: SymplecticTableau,
    l_post_selects: Vec<(usize, PauliXZ, bool)>,
    r_post_selects: Vec<(usize, PauliXZ, bool)>,
}

impl SymplecticTableau {
    pub fn new(nb_qubits: usize) -> Self {
        SymplecticTableau {
            nb_qubits,
            nb_stabs: 0,
            z: vec![],
            x: vec![],
            signs: BitVector::new(0),
        }
    }

    pub fn add_stab(&mut self, z: BitVector, x: BitVector, sign: bool) -> usize {
        let stab_id = self.nb_stabs;
        self.z.push(z);
        self.x.push(x);
        self.signs.extend_vec(vec![sign], self.nb_stabs);
        self.nb_stabs += 1;
        stab_id
    }

    pub fn add_string(&mut self, pauli: &str, sign: bool) -> Result<usize, String> {
        assert!(pauli.len() <= self.nb_qubits);
        let mut z = BitVector::new(self.nb_qubits);
        let mut x = BitVector::new(self.nb_qubits);
        for (i, ch) in pauli.chars().enumerate() {
            match ch {
                'I' | 'i' | ' ' => {}
                'X' | 'x' => {
                    x.xor_bit(i);
                }
                'Y' | 'y' => {
                    x.xor_bit(i);
                    z.xor_bit(i);
                }
                'Z' | 'z' => {
                    z.xor_bit(i);
                }
                _ => {
                    return Err("Non-Pauli letter encountered in SymplecticTableau::add_string. Please only use {'I', 'X', 'Y', 'Z'}.".to_string());
                }
            }
        }
        return Ok(self.add_stab(z, x, sign));
    }

    pub fn stab_as_string(&self, stab: usize) -> String {
        let mut s = String::from("");
        if self.signs.get(stab) {
            s.push('-');
        } else {
            s.push('+');
        }
        for q in 0..self.nb_qubits {
            match (self.x[stab].get(q), self.z[stab].get(q)) {
                (false, false) => {
                    s.push(' ');
                }
                (false, true) => {
                    s.push('Z');
                }
                (true, false) => {
                    s.push('X');
                }
                (true, true) => {
                    s.push('Y');
                }
            }
        }
        s
    }

    pub fn add_qubits(&mut self, nb_new_qbs: usize) -> usize {
        let qb_base = self.nb_qubits;
        self.nb_qubits += nb_new_qbs;
        for zv in &mut self.z {
            zv.extend_vec(vec![false; nb_new_qbs], qb_base);
        }
        for xv in &mut self.x {
            xv.extend_vec(vec![false; nb_new_qbs], qb_base);
        }
        qb_base
    }

    pub fn add_qubit(&mut self) -> usize {
        self.add_qubits(1)
    }

    pub fn add_n_qubits<const N: usize>(&mut self) -> [usize; N] {
        let col = self.add_qubits(N);
        (col..col + N).collect_array().unwrap()
    }

    pub fn append_z(&mut self, qubit: usize) {
        for (i, xv) in self.x.iter().enumerate() {
            if xv.get(qubit) {
                self.signs.xor_bit(i);
            }
        }
    }

    pub fn append_x(&mut self, qubit: usize) {
        for (i, zv) in self.z.iter().enumerate() {
            if zv.get(qubit) {
                self.signs.xor_bit(i);
            }
        }
    }

    pub fn append_s(&mut self, qubit: usize) {
        for (i, xv) in self.x.iter().enumerate() {
            if xv.get(qubit) {
                let zv: &mut BitVector = self.z.get_mut(i).unwrap();
                if zv.get(qubit) {
                    self.signs.xor_bit(i);
                }
                zv.xor_bit(qubit);
            }
        }
    }

    pub fn append_v(&mut self, qubit: usize) {
        for (i, zv) in self.z.iter().enumerate() {
            if zv.get(qubit) {
                let xv: &mut BitVector = self.x.get_mut(i).unwrap();
                if !xv.get(qubit) {
                    self.signs.xor_bit(i);
                }
                xv.xor_bit(qubit);
            }
        }
    }

    pub fn append_h(&mut self, qubit: usize) {
        for (i, (zv, xv)) in zip(self.z.iter_mut(), self.x.iter_mut()).enumerate() {
            let z = zv.get(qubit);
            let x = xv.get(qubit);
            // Swap values
            if z ^ x {
                zv.xor_bit(qubit);
                xv.xor_bit(qubit);
            }
            // Phase flip if Y
            if z && x {
                self.signs.xor_bit(i);
            }
        }
    }

    pub fn append_cx(&mut self, ctrl: usize, trgt: usize) {
        for (i, (zv, xv)) in zip(self.z.iter_mut(), self.x.iter_mut()).enumerate() {
            let zc = zv.get(ctrl);
            let zt = zv.get(trgt);
            let xc = xv.get(ctrl);
            let xt = xv.get(trgt);
            // Phase flip if XZ or YY
            if xc && zt && !(zc ^ xt) {
                self.signs.xor_bit(i);
            }
            // If xc, flip xt
            if xc {
                xv.xor_bit(trgt);
            }
            // If zt, flip zc
            if zt {
                zv.xor_bit(ctrl);
            }
        }
    }

    pub fn append_cy(&mut self, ctrl: usize, trgt: usize) {
        for (i, (zv, xv)) in zip(self.z.iter_mut(), self.x.iter_mut()).enumerate() {
            let zc = zv.get(ctrl);
            let zt = zv.get(trgt);
            let xc = xv.get(ctrl);
            let xt = xv.get(trgt);
            // Phase flip if XZ or YX
            if xc && ((!zc && !xt && zt) || (zc && xt && !zt)) {
                self.signs.xor_bit(i);
            }
            // If xc, flip zt and xt
            if xc {
                xv.xor_bit(trgt);
                zv.xor_bit(trgt);
            }
            // If zt ^ xt, flip zc
            if zt ^ xt {
                zv.xor_bit(ctrl);
            }
        }
    }

    pub fn append_cz(&mut self, ctrl: usize, trgt: usize) {
        for (i, (zv, xv)) in zip(self.z.iter_mut(), self.x.iter_mut()).enumerate() {
            let zc = zv.get(ctrl);
            let zt = zv.get(trgt);
            let xc = xv.get(ctrl);
            let xt = xv.get(trgt);
            // Phase flip if XX or YY
            if xc && xt && !(zc ^ zt) {
                self.signs.xor_bit(i);
            }
            // If xc, flip zt
            if xc {
                zv.xor_bit(trgt);
            }
            // If xt, flip zc
            if xt {
                zv.xor_bit(ctrl);
            }
        }
    }

    pub fn append_swap(&mut self, q0: usize, q1: usize) {
        for (zv, xv) in zip(self.z.iter_mut(), self.x.iter_mut()) {
            // To swap, just negate both bits if they differ
            if zv.get(q0) ^ zv.get(q1) {
                zv.xor_bit(q0);
                zv.xor_bit(q1);
            }
            if xv.get(q0) ^ xv.get(q1) {
                xv.xor_bit(q0);
                xv.xor_bit(q1);
            }
        }
    }

    // Compute i^coeff stabs[sr] * stabs[sw] and store in stabs[sw]
    pub fn stab_mult(&mut self, sr: usize, sw: usize, coeff: usize) {
        let zr = self.z.get(sr).unwrap().clone();
        let xr = self.x.get(sr).unwrap().clone();
        let zw = self.z.get_mut(sw).unwrap();
        let xw = self.x.get_mut(sw).unwrap();
        let mut num_is = coeff;
        // i for each Y=iXZ in each input string
        let mut yr = xr.clone();
        yr.and(&zr);
        let mut yw = xw.clone();
        yw.and(zw);
        // num_is += yr.get_all_ones(self.nb_qubits).len() + yw.get_all_ones(self.nb_qubits).len();
        num_is += ((yr.popcount() + yw.popcount()) % 4) as usize;
        // -1 for reordering (xr, zr, xw, zw) to (xr, xw, zr, zw)
        let mut zr_and_xw = zr.clone();
        zr_and_xw.and(xw);
        // num_is += 2 * zr_and_xw.get_all_ones(self.nb_qubits).len();
        num_is += 2 * ((zr_and_xw.popcount() % 4) as usize);
        // Calculate output string
        zw.xor(&zr);
        xw.xor(&xr);
        // -i for each Y=iXZ in output string
        let mut yw = xw.clone();
        yw.and(zw);
        // num_is += 3 * yw.get_all_ones(self.nb_qubits).len();
        num_is += 3 * ((yw.popcount() % 4) as usize);
        // Adjust sign
        if self.signs.get(sr) ^ (num_is % 4 == 2) {
            self.signs.xor_bit(sw);
        }
    }

    // Removes a stabilizer from the tableau
    // If the stabilizer to be removed was the last one, returns None
    // Otherwise, in order to keep things dense, swap with the last stabilizer before removing; returns the index of the last stabilizer, i.e. the old index that is now at to_delete
    pub fn delete_stab(&mut self, to_delete: usize) -> Option<usize> {
        self.nb_stabs -= 1;
        if to_delete == self.nb_stabs {
            self.z.pop();
            self.x.pop();
            // BitVector has no record of the number of bits it contains, so we just reset the bit in case it gets reused later
            if self.signs.get(self.nb_stabs) {
                self.signs.xor_bit(self.nb_stabs);
            }
            None
        } else {
            // Overwrite with last stabilizer
            self.z[to_delete] = self.z.pop().unwrap();
            self.x[to_delete] = self.x.pop().unwrap();
            if self.signs.get(to_delete) != self.signs.get(self.nb_stabs) {
                self.signs.xor_bit(to_delete);
            }
            // BitVector has no record of the number of bits it contains, so we just reset the bit in case it gets reused later
            if self.signs.get(self.nb_stabs) {
                self.signs.xor_bit(self.nb_stabs);
            }
            Some(self.nb_stabs)
        }
    }

    // Removes a qubit from the tableau
    // If the qubit to be removed was the last one, returns None
    // Otherwise, in order to keep things dense, swap with the last qubit before removing; returns the index of the last qubit, i.e. the old index that is now at to_delete
    pub fn delete_qubit(&mut self, to_delete: usize) -> Option<usize> {
        self.nb_qubits -= 1;
        if to_delete == self.nb_qubits {
            // If any stabilizers involve the qubit, we cannot delete
            for zv in self.z.iter() {
                assert!(!zv.get(self.nb_qubits));
            }
            for xv in self.x.iter() {
                assert!(!xv.get(self.nb_qubits));
            }
            // BitVector has no record of the number of bits it contains, so we can just leave the bits set as 0
            None
        } else {
            // If any stabilizers involve the qubit, we cannot delete
            // Move any value from the last qubit to to_delete and reset the last element in the BitVector so it may be safely reused later
            for zv in self.z.iter_mut() {
                assert!(!zv.get(to_delete));
                if zv.get(self.nb_qubits) {
                    zv.xor_bit(to_delete);
                    zv.xor_bit(self.nb_qubits);
                }
            }
            for xv in self.x.iter_mut() {
                assert!(!xv.get(to_delete));
                if xv.get(self.nb_qubits) {
                    xv.xor_bit(to_delete);
                    xv.xor_bit(self.nb_qubits);
                }
            }
            Some(self.nb_qubits)
        }
    }

    // Reduce to row echelon form over the stabilizers
    // Given the ordering of columns (qubit, z/x), call stab_mult to achieve reduced row-echelon form
    // col_order need not include every column, in which case we terminate after solving just the columns provided
    // Feel free to suggest a better interface here
    // We may also want a version that allows us to simultaneously perform this over a pair of tableaux
    pub fn echelon(&mut self, col_order: &Vec<(usize, PauliXZ)>) {
        let mut pivot_stab = 0;
        for (qubit, p) in col_order {
            match p {
                PauliXZ::X => {
                    let mut pivot_found = false;
                    // Find next row
                    for i in pivot_stab..self.nb_stabs {
                        if self.x[i].get(*qubit) {
                            // Found new stabilizer to pivot
                            pivot_found = true;
                            if i != pivot_stab {
                                // Make sure pivot_stab contains this element
                                self.stab_mult(i, pivot_stab, 0);
                            }
                            break;
                        }
                    }
                    // Eliminate entries from all other rows
                    if pivot_found {
                        for i in 0..self.nb_stabs {
                            if (i != pivot_stab) && self.x[i].get(*qubit) {
                                self.stab_mult(pivot_stab, i, 0);
                            }
                        }
                        pivot_stab += 1;
                    }
                }
                PauliXZ::Z => {
                    let mut pivot_found = false;
                    // Find next row
                    for i in pivot_stab..self.nb_stabs {
                        if self.z[i].get(*qubit) {
                            // Found new stabilizer to pivot
                            pivot_found = true;
                            if i != pivot_stab {
                                // Make sure pivot_stab contains this element
                                self.stab_mult(i, pivot_stab, 0);
                            }
                            break;
                        }
                    }
                    // Eliminate entries from all other rows
                    if pivot_found {
                        for i in 0..self.nb_stabs {
                            if (i != pivot_stab) && self.z[i].get(*qubit) {
                                self.stab_mult(pivot_stab, i, 0);
                            }
                        }
                        pivot_stab += 1;
                    }
                }
            }
        }
    }

    pub fn all_columns(&self) -> Vec<(usize, PauliXZ)> {
        interleave(
            (0..self.nb_qubits).map(|c| (c, PauliXZ::X)),
            (0..self.nb_qubits).map(|c| (c, PauliXZ::Z)),
        )
        .collect_vec()
    }

    // Call echelon to minimise the number of rows with non-zero components in the given columns, then remove those rows with such non-zero components
    pub fn project_cols_to_zero(&mut self, cols: &Vec<(usize, PauliXZ)>) {
        self.echelon(cols);
        let mut num_to_remove = 0;
        for (qubit, p) in cols {
            match p {
                PauliXZ::X => {
                    if self.x[num_to_remove].get(*qubit) {
                        num_to_remove += 1;
                    }
                }
                PauliXZ::Z => {
                    if self.z[num_to_remove].get(*qubit) {
                        num_to_remove += 1;
                    }
                }
            }
        }
        // Even though stabs to remove will be at the top, if num_to_remove is greater than nb_stabs/2 we can choose an order which maximises the number of stab removals from the end which are cheaper as they don't involve moving rows around
        let num_remaining = self.nb_stabs - num_to_remove;
        for i in 0..min(num_to_remove, num_remaining) {
            self.delete_stab(i);
        }
        for i in (num_remaining..num_to_remove).rev() {
            self.delete_stab(i);
        }
    }

    pub fn anticommutes_with(&mut self, stab: usize, z: &BitVector, x: &BitVector) -> bool {
        let mut sz_and_x = self.z.get(stab).unwrap().clone();
        sz_and_x.and(x);
        let mut sx_and_z = self.x.get(stab).unwrap().clone();
        sx_and_z.and(z);
        sz_and_x.xor(&sx_and_z);
        (sz_and_x.popcount() % 2) == 1
    }

    // Apply row combinations to leave at most one row anticommuting with the target Pauli string, and remove it
    pub fn project_commuting_with(&mut self, z: &BitVector, x: &BitVector) {
        let mut anticommuting_stab: Option<usize> = None;
        for i in 0..self.nb_stabs {
            if self.anticommutes_with(i, z, x) {
                match anticommuting_stab {
                    Some(ac_stab) => {
                        self.stab_mult(ac_stab, i, 0);
                    }
                    None => {
                        anticommuting_stab = Some(i);
                    }
                }
            }
        }
        if let Some(stab) = anticommuting_stab {
            self.delete_stab(stab);
        }
    }

    // Given a set of Pauli strings of weight 1 (i.e. +-Z or +-X on a single qubit), post-select on them
    // Does not include the post-selected strings in the resulting tableau
    pub fn post_select_1qs(&mut self, cols: &Vec<(usize, PauliXZ, bool)>) {
        let cols_to_remove = cols
            .iter()
            .map(|(q, xz, _ph)| match xz {
                PauliXZ::X => (*q, PauliXZ::Z),
                PauliXZ::Z => (*q, PauliXZ::X),
            })
            .collect_vec();
        self.project_cols_to_zero(&cols_to_remove);
        let mut z_flip_mask = BitVector::new(self.nb_qubits);
        let mut x_flip_mask = BitVector::new(self.nb_qubits);
        let mut z_clear_mask = BitVector::new(self.nb_qubits);
        let mut x_clear_mask = BitVector::new(self.nb_qubits);
        z_clear_mask.negate();
        x_clear_mask.negate();
        for (q, xz, ph) in cols {
            match xz {
                PauliXZ::X => {
                    x_clear_mask.xor_bit(*q);
                    if *ph {
                        x_flip_mask.xor_bit(*q);
                    }
                }
                PauliXZ::Z => {
                    z_clear_mask.xor_bit(*q);
                    if *ph {
                        z_flip_mask.xor_bit(*q);
                    }
                }
            }
        }
        for i in 0..self.nb_stabs {
            let mut z_flips = z_flip_mask.clone();
            z_flips.and(&self.z[i]);
            let mut x_flips = x_flip_mask.clone();
            x_flips.and(&self.x[i]);
            self.z[i].and(&z_clear_mask);
            self.x[i].and(&x_clear_mask);
            if (z_flips.popcount() + x_flips.popcount()) % 2 == 1 {
                self.signs.xor_bit(i);
            }
        }
    }

    pub fn joint_decomposition(l: &SymplecticTableau, r: &SymplecticTableau) -> JointDecomposition {
        let mut left = l.clone();
        let mut right = r.clone();
        // Assumes all stabs in left mutually commute, and same for right.
        // Assumes left and right have the same qubit number and ordering.
        // Jointly ac_pivot left and right to isolate anti-commuting rows at the top and make sure they only anti-commute within their pairs
        let mut ac_pivot = 0;
        for i in 0..left.nb_stabs {
            // Stabs in left and right up to ac_pivot are already in pairs; search for a new pair below here
            let mut r_ac_with_l_i: Option<usize> = None;
            for j in ac_pivot..right.nb_stabs {
                if right.anticommutes_with(j, left.z.get(i).unwrap(), left.x.get(i).unwrap()) {
                    r_ac_with_l_i = Some(j);
                    break;
                }
            }
            if r_ac_with_l_i.is_none() {
                continue;
            }
            let j = r_ac_with_l_i.unwrap();
            if i != ac_pivot {
                // Move stab i to ac_pivot in left
                left.z.swap(i, ac_pivot);
                left.x.swap(i, ac_pivot);
                if left.signs.get(i) != left.signs.get(ac_pivot) {
                    left.signs.xor_bit(i);
                    left.signs.xor_bit(ac_pivot);
                }
            }
            if j != ac_pivot {
                // Move stab j to ac_pivot in right
                right.z.swap(j, ac_pivot);
                right.x.swap(j, ac_pivot);
                if right.signs.get(j) != right.signs.get(ac_pivot) {
                    right.signs.xor_bit(j);
                    right.signs.xor_bit(ac_pivot);
                }
            }
            // right[ac_pivot] already commutes with stabs in left up to ac_pivot; make sure it commutes with those after
            for k in (ac_pivot + 1)..left.nb_stabs {
                if left.anticommutes_with(
                    k,
                    right.z.get(ac_pivot).unwrap(),
                    right.x.get(ac_pivot).unwrap(),
                ) {
                    left.stab_mult(ac_pivot, k, 0);
                }
            }
            // left[ac_pivot] already commutes with stabs in right up to ac_pivot; make sure it commutes with those after
            for k in (ac_pivot + 1)..right.nb_stabs {
                if right.anticommutes_with(
                    k,
                    left.z.get(ac_pivot).unwrap(),
                    left.x.get(ac_pivot).unwrap(),
                ) {
                    right.stab_mult(ac_pivot, k, 0);
                }
            }
            ac_pivot += 1;
        }

        // Remove these anti-commuting pairs and store them in our final tableau.
        let mut res = SymplecticTableau::new(left.nb_qubits);
        // Remove in reverse order to minimise number of row moves.
        for i in (0..ac_pivot).rev() {
            res.add_stab(
                left.z.get(i).unwrap().clone(),
                left.x.get(i).unwrap().clone(),
                left.signs.get(i),
            );
            left.delete_stab(i);
            res.add_stab(
                right.z.get(i).unwrap().clone(),
                right.x.get(i).unwrap().clone(),
                right.signs.get(i),
            );
            right.delete_stab(i);
        }

        // From now on, remaining rows of L and R all mutually commute.
        // We begin by explaining how to find the strings that can be generated in both, ignoring phase.
        // We do this by initialising two new tableaus using the following stacks:
        // / L | L \
        // \ R | 0 /
        // Then, if we perform simultaneous row combinations to convert the lhs into row echelon form (no need for reduced row echelon),
        // strings common to both will appear at the bottom of rhs whenever the lhs is the identity string.
        // The phase on rhs will match the phases of that string in left; the phase on lhs will tell us whether the phases of that string agree or disagree between left and right.
        // The rhs still needs to generate L. In order to get just the additional generators, we row reduce the tableau, prioritising picking pivot rows from the bottom segment, and never moving rows between the segments. This preserves the property that the bottom segment generates the common string subgroup, but the total number of non-zero rows is equal to L.nb_stabs, and therefore the remaining non-zero rows in the top segment are a minimal set of additional generators for L that are not in R.
        // To then identify the extra stabs for generating R, we can add an additional tableau that gets simultaneously reduced in the same procedure from which we can obtain its specific stabilizers in the same way.
        // The reduction on the combined tableaus now looks like
        // / L | L | 0 \     / A+B                  | A                      | B                      \
        // \ R | 0 | R / --> \ 0 (Phase as in Diff) | Common (Phase as in L) | Common (Phase as in R) /
        // Then
        // / A          \     / JustL       \     / B          \     / JustR        \
        // \ Common (L) / --> \ Common' (L) / and \ Common (R) / --> \ Common'' (R) /

        let mut lr_tab = left.clone();
        let mut l0_tab = left.clone();
        let mut r0_tab = SymplecticTableau::new(right.nb_qubits);
        for _ in 0..left.nb_stabs {
            r0_tab.add_stab(
                BitVector::new(left.nb_qubits),
                BitVector::new(left.nb_qubits),
                false,
            );
        }
        for i in 0..right.nb_stabs {
            lr_tab.add_stab(right.z[i].clone(), right.x[i].clone(), right.signs.get(i));
            l0_tab.add_stab(
                BitVector::new(left.nb_qubits),
                BitVector::new(left.nb_qubits),
                false,
            );
            r0_tab.add_stab(right.z[i].clone(), right.x[i].clone(), right.signs.get(i));
        }

        // Perform simultaneous row combinations to convert lr_tab into row echelon form (no need for reduced row echelon)
        let mut lr_pivot = 0;
        for q in 0..lr_tab.nb_qubits {
            // Reduce X column
            let mut pivot_found = false;
            for i in lr_pivot..lr_tab.nb_stabs {
                if lr_tab.x[i].get(q) {
                    // Found new stabilizer to pivot
                    pivot_found = true;
                    if i != lr_pivot {
                        // Make sure lr_pivot contains this element
                        lr_tab.stab_mult(i, lr_pivot, 0);
                        l0_tab.stab_mult(i, lr_pivot, 0);
                        r0_tab.stab_mult(i, lr_pivot, 0);
                    }
                    break;
                }
            }
            // Eliminate entries from lower rows
            if pivot_found {
                for i in (lr_pivot + 1)..lr_tab.nb_stabs {
                    if lr_tab.x[i].get(q) {
                        lr_tab.stab_mult(lr_pivot, i, 0);
                        l0_tab.stab_mult(lr_pivot, i, 0);
                        r0_tab.stab_mult(lr_pivot, i, 0);
                    }
                }
                lr_pivot += 1;
            }
            // Reduce Z column
            pivot_found = false;
            for i in lr_pivot..lr_tab.nb_stabs {
                if lr_tab.z[i].get(q) {
                    // Found new stabilizer to pivot
                    pivot_found = true;
                    if i != lr_pivot {
                        // Make sure lr_pivot contains this element
                        lr_tab.stab_mult(i, lr_pivot, 0);
                        l0_tab.stab_mult(i, lr_pivot, 0);
                        r0_tab.stab_mult(i, lr_pivot, 0);
                    }
                    break;
                }
            }
            // Eliminate entries from lower rows
            if pivot_found {
                for i in (lr_pivot + 1)..lr_tab.nb_stabs {
                    if lr_tab.z[i].get(q) {
                        lr_tab.stab_mult(lr_pivot, i, 0);
                        l0_tab.stab_mult(lr_pivot, i, 0);
                        r0_tab.stab_mult(lr_pivot, i, 0);
                    }
                }
                lr_pivot += 1;
            }
        }

        // lr_pivot is now the index of the first row without any string in lr_tab.
        // Take row combinations so at most one of the common rows has a disagreement on the phase
        // Copy out the common strings to a temporary tableau
        let mut phase_flip_index: Option<usize> = None;
        let mut common_tab = SymplecticTableau::new(l0_tab.nb_qubits);
        for i in lr_pivot..lr_tab.nb_stabs {
            let new_stab = common_tab.add_stab(
                l0_tab.z.get(i).unwrap().clone(),
                l0_tab.x.get(i).unwrap().clone(),
                l0_tab.signs.get(i),
            );
            if lr_tab.signs.get(i) {
                match phase_flip_index {
                    Some(pfi) => {
                        common_tab.stab_mult(pfi, new_stab, 0);
                    }
                    None => {
                        phase_flip_index = Some(new_stab);
                    }
                }
            }
        }

        // Special row reduction of l0_tab with preservation of lower space
        let mut l0_top_pivot = 0;
        let mut l0_bottom_pivot = lr_pivot;
        for q in 0..l0_tab.nb_qubits {
            // Reduce X column
            let mut bottom_pivot_found = false;
            for i in l0_bottom_pivot..l0_tab.nb_stabs {
                if l0_tab.x[i].get(q) {
                    bottom_pivot_found = true;
                    if i != l0_bottom_pivot {
                        l0_tab.stab_mult(i, l0_bottom_pivot, 0);
                    }
                    break;
                }
            }
            if bottom_pivot_found {
                for i in l0_top_pivot..lr_pivot {
                    if l0_tab.x[i].get(q) {
                        l0_tab.stab_mult(l0_bottom_pivot, i, 0);
                    }
                }
                for i in (l0_bottom_pivot + 1)..l0_tab.nb_stabs {
                    if l0_tab.x[i].get(q) {
                        l0_tab.stab_mult(l0_bottom_pivot, i, 0);
                    }
                }
                l0_bottom_pivot += 1;
            } else {
                let mut top_pivot_found = false;
                for i in l0_top_pivot..lr_pivot {
                    if l0_tab.x[i].get(q) {
                        top_pivot_found = true;
                        if i != l0_top_pivot {
                            l0_tab.stab_mult(i, l0_top_pivot, 0);
                        }
                        break;
                    }
                }
                if top_pivot_found {
                    for i in (l0_top_pivot + 1)..lr_pivot {
                        if l0_tab.x[i].get(q) {
                            l0_tab.stab_mult(l0_top_pivot, i, 0);
                        }
                    }
                    l0_top_pivot += 1;
                }
            }
            // Reduce Z column
            let mut bottom_pivot_found = false;
            for i in l0_bottom_pivot..l0_tab.nb_stabs {
                if l0_tab.z[i].get(q) {
                    bottom_pivot_found = true;
                    if i != l0_bottom_pivot {
                        l0_tab.stab_mult(i, l0_bottom_pivot, 0);
                    }
                    break;
                }
            }
            if bottom_pivot_found {
                for i in l0_top_pivot..lr_pivot {
                    if l0_tab.z[i].get(q) {
                        l0_tab.stab_mult(l0_bottom_pivot, i, 0);
                    }
                }
                for i in (l0_bottom_pivot + 1)..l0_tab.nb_stabs {
                    if l0_tab.z[i].get(q) {
                        l0_tab.stab_mult(l0_bottom_pivot, i, 0);
                    }
                }
                l0_bottom_pivot += 1;
            } else {
                let mut top_pivot_found = false;
                for i in l0_top_pivot..lr_pivot {
                    if l0_tab.z[i].get(q) {
                        top_pivot_found = true;
                        if i != l0_top_pivot {
                            l0_tab.stab_mult(i, l0_top_pivot, 0);
                        }
                        break;
                    }
                }
                if top_pivot_found {
                    for i in (l0_top_pivot + 1)..lr_pivot {
                        if l0_tab.z[i].get(q) {
                            l0_tab.stab_mult(l0_top_pivot, i, 0);
                        }
                    }
                    l0_top_pivot += 1;
                }
            }
        }
        // Now l0_tab[0..l0_top_pivot] give the additional generators needed to span L; add them to the final result tableau
        for i in 0..l0_top_pivot {
            res.add_stab(
                l0_tab.z.get(i).unwrap().clone(),
                l0_tab.x.get(i).unwrap().clone(),
                l0_tab.signs.get(i),
            );
        }

        // Now we do the same with r0_tab to get the additional generators for R
        let mut r0_top_pivot = 0;
        let mut r0_bottom_pivot = lr_pivot;
        for q in 0..r0_tab.nb_qubits {
            // Reduce X column
            let mut bottom_pivot_found = false;
            for i in r0_bottom_pivot..r0_tab.nb_stabs {
                if r0_tab.x[i].get(q) {
                    bottom_pivot_found = true;
                    if i != r0_bottom_pivot {
                        r0_tab.stab_mult(i, r0_bottom_pivot, 0);
                    }
                    break;
                }
            }
            if bottom_pivot_found {
                for i in r0_top_pivot..lr_pivot {
                    if r0_tab.x[i].get(q) {
                        r0_tab.stab_mult(r0_bottom_pivot, i, 0);
                    }
                }
                for i in (r0_bottom_pivot + 1)..r0_tab.nb_stabs {
                    if r0_tab.x[i].get(q) {
                        r0_tab.stab_mult(r0_bottom_pivot, i, 0);
                    }
                }
                r0_bottom_pivot += 1;
            } else {
                let mut top_pivot_found = false;
                for i in r0_top_pivot..lr_pivot {
                    if r0_tab.x[i].get(q) {
                        top_pivot_found = true;
                        if i != r0_top_pivot {
                            r0_tab.stab_mult(i, r0_top_pivot, 0);
                        }
                        break;
                    }
                }
                if top_pivot_found {
                    for i in (r0_top_pivot + 1)..lr_pivot {
                        if r0_tab.x[i].get(q) {
                            r0_tab.stab_mult(r0_top_pivot, i, 0);
                        }
                    }
                    r0_top_pivot += 1;
                }
            }
            // Reduce Z column
            let mut bottom_pivot_found = false;
            for i in r0_bottom_pivot..r0_tab.nb_stabs {
                if r0_tab.z[i].get(q) {
                    bottom_pivot_found = true;
                    if i != r0_bottom_pivot {
                        r0_tab.stab_mult(i, r0_bottom_pivot, 0);
                    }
                    break;
                }
            }
            if bottom_pivot_found {
                for i in r0_top_pivot..lr_pivot {
                    if r0_tab.z[i].get(q) {
                        r0_tab.stab_mult(r0_bottom_pivot, i, 0);
                    }
                }
                for i in (r0_bottom_pivot + 1)..r0_tab.nb_stabs {
                    if r0_tab.z[i].get(q) {
                        r0_tab.stab_mult(r0_bottom_pivot, i, 0);
                    }
                }
                r0_bottom_pivot += 1;
            } else {
                let mut top_pivot_found = false;
                for i in r0_top_pivot..lr_pivot {
                    if r0_tab.z[i].get(q) {
                        top_pivot_found = true;
                        if i != r0_top_pivot {
                            r0_tab.stab_mult(i, r0_top_pivot, 0);
                        }
                        break;
                    }
                }
                if top_pivot_found {
                    for i in (r0_top_pivot + 1)..lr_pivot {
                        if r0_tab.z[i].get(q) {
                            r0_tab.stab_mult(r0_top_pivot, i, 0);
                        }
                    }
                    r0_top_pivot += 1;
                }
            }
        }
        for i in 0..r0_top_pivot {
            res.add_stab(
                r0_tab.z.get(i).unwrap().clone(),
                r0_tab.x.get(i).unwrap().clone(),
                r0_tab.signs.get(i),
            );
        }

        if let Some(pfi) = phase_flip_index {
            res.add_stab(
                common_tab.z.get(pfi).unwrap().clone(),
                common_tab.x.get(pfi).unwrap().clone(),
                common_tab.signs.get(pfi),
            );
        }
        for i in 0..common_tab.nb_stabs {
            if phase_flip_index != Some(i) {
                res.add_stab(
                    common_tab.z.get(i).unwrap().clone(),
                    common_tab.x.get(i).unwrap().clone(),
                    common_tab.signs.get(i),
                );
            }
        }

        JointDecomposition {
            tab: res,
            n_ac_pairs: ac_pivot,
            just_left: l0_top_pivot,
            just_right: r0_top_pivot,
            phase_flip_term: phase_flip_index.is_some(),
        }
    }

    pub fn join(left: &SymplecticTableau, right: &SymplecticTableau) -> SymplecticTableau {
        let jd = SymplecticTableau::joint_decomposition(left, right);
        let mut res = SymplecticTableau::new(jd.tab.nb_qubits);
        let (join_begin, join_end) = jd.join_range();
        for i in join_begin..join_end {
            res.add_stab(
                jd.tab.z.get(i).unwrap().clone(),
                jd.tab.x.get(i).unwrap().clone(),
                jd.tab.signs.get(i),
            );
        }
        res
    }

    pub fn controlled_meet(left: &SymplecticTableau, right: &SymplecticTableau) -> ControlledMeet {
        let jd = SymplecticTableau::joint_decomposition(left, right);
        let mut cm = ControlledMeet {
            tab: jd.tab.clone(),
            l_post_selects: vec![],
            r_post_selects: vec![],
        };
        let ac_control_begin = cm.tab.add_qubits(jd.n_ac_pairs);
        for i in 0..jd.n_ac_pairs {
            cm.tab.z[2 * i].xor_bit(ac_control_begin + i);
            cm.l_post_selects
                .push((ac_control_begin + i, PauliXZ::Z, false));
            cm.tab.x[2 * i + 1].xor_bit(ac_control_begin + i);
            cm.r_post_selects
                .push((ac_control_begin + i, PauliXZ::X, false));
        }
        let l_control_begin = cm.tab.add_qubits(jd.just_left);
        let (l_begin, _) = jd.just_left_range();
        for i in 0..jd.just_left {
            cm.tab.z[l_begin + i].xor_bit(l_control_begin + i);
            cm.l_post_selects
                .push((l_control_begin + i, PauliXZ::Z, false));
            cm.r_post_selects
                .push((l_control_begin + i, PauliXZ::X, false));
        }
        let r_control_begin = cm.tab.add_qubits(jd.just_right);
        let (r_begin, _) = jd.just_right_range();
        for i in 0..jd.just_right {
            cm.tab.x[r_begin + i].xor_bit(r_control_begin + i);
            cm.l_post_selects
                .push((r_control_begin + i, PauliXZ::Z, false));
            cm.r_post_selects
                .push((r_control_begin + i, PauliXZ::X, false));
        }
        if let Some(pfi) = jd.phase_flip_term_index() {
            let phase_control = cm.tab.add_qubit();
            cm.tab.z[pfi].xor_bit(phase_control);
            cm.l_post_selects.push((phase_control, PauliXZ::Z, false));
            cm.r_post_selects.push((phase_control, PauliXZ::Z, true));
        }
        cm
    }
}

impl Display for SymplecticTableau {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        for i in 0..self.nb_stabs {
            writeln!(f, "{}", self.stab_as_string(i))?;
        }
        Ok(())
    }
}

#[cfg(test)]
mod test {
    use crate::symplectic_tableau::SymplecticTableau;

    #[test]
    fn test_joint_decomposition() {
        let mut l = SymplecticTableau::new(5);
        l.add_string("ZIZII", false).ok();
        l.add_string("XIXIX", false).ok();
        l.add_string("IIZIZ", false).ok();
        l.add_string("IZIZI", false).ok();
        l.add_string("IXIYI", false).ok();
        let mut r = SymplecticTableau::new(5);
        r.add_string("ZIZII", true).ok();
        r.add_string("XIXII", false).ok();
        r.add_string("IZIZI", false).ok();
        r.add_string("IXIXI", false).ok();
        let jd = SymplecticTableau::joint_decomposition(&l, &r);
        assert_eq!(jd.n_ac_pairs, 2);
        assert_eq!(jd.ac_range(), (0, 4));
        assert_eq!(jd.just_left, 1);
        assert_eq!(jd.just_left_range(), (4, 5));
        assert_eq!(jd.just_right, 0);
        assert_eq!(jd.just_right_range(), (5, 5));
        assert_eq!(jd.phase_flip_term, true);
        assert_eq!(jd.phase_flip_term_index(), Some(5));
        assert_eq!(jd.join_range(), (6, 7));
        assert_eq!(jd.tab.stab_as_string(0), "+ X Y ");
        assert_eq!(jd.tab.stab_as_string(1), "+ X X ");
        assert_eq!(jd.tab.stab_as_string(2), "+  Z Z");
        assert_eq!(jd.tab.stab_as_string(3), "+X X  ");
        assert_eq!(jd.tab.stab_as_string(4), "+XZXZX");
        assert_eq!(jd.tab.stab_as_string(5), "+Z Z  ");
        assert_eq!(jd.tab.stab_as_string(6), "+ Z Z ");
    }

    #[test]
    fn test_controlled_meet_by_projections() {
        let mut l = SymplecticTableau::new(5);
        l.add_string("ZIZII", false).ok();
        l.add_string("XIXIX", false).ok();
        l.add_string("IIZIZ", false).ok();
        l.add_string("IZIZI", false).ok();
        l.add_string("IXIYI", false).ok();
        let mut r = SymplecticTableau::new(5);
        r.add_string("ZIZII", true).ok();
        r.add_string("XIXII", false).ok();
        r.add_string("IZIZI", false).ok();
        r.add_string("IXIXI", false).ok();
        let cm = SymplecticTableau::controlled_meet(&l, &r);
        let mut cm_l = cm.tab.clone();
        cm_l.post_select_1qs(&cm.l_post_selects);
        cm_l.echelon(&cm_l.all_columns());
        l.echelon(&l.all_columns());
        assert_eq!(cm_l.nb_stabs, l.nb_stabs);
        l.add_qubits(cm_l.nb_qubits - l.nb_qubits);
        for i in 0..l.nb_stabs {
            assert_eq!(l.stab_as_string(i), cm_l.stab_as_string(i));
        }
        let mut cm_r = cm.tab.clone();
        cm_r.post_select_1qs(&cm.r_post_selects);
        cm_r.echelon(&cm_r.all_columns());
        r.echelon(&r.all_columns());
        assert_eq!(cm_r.nb_stabs, r.nb_stabs);
        r.add_qubits(cm_r.nb_qubits - r.nb_qubits);
        for i in 0..r.nb_stabs {
            assert_eq!(r.stab_as_string(i), cm_r.stab_as_string(i));
        }
    }

    #[test]
    fn test_successive_controlled_meets() {
        // Each of these tableaus is some number of repetitions of
        // q0 -.--
        //     |
        // q1 -+.-
        //      |
        // q2 --+-
        let mut tab1 = SymplecticTableau::new(6);
        tab1.add_string("ZIIZII", false).ok();
        tab1.add_string("XIIXXX", false).ok();
        tab1.add_string("IZIZZI", false).ok();
        tab1.add_string("IXIIXX", false).ok();
        tab1.add_string("IIZIZZ", false).ok();
        tab1.add_string("IIXIIX", false).ok();
        let mut tab2 = SymplecticTableau::new(6);
        tab2.add_string("ZIIZII", false).ok();
        tab2.add_string("XIIXIX", false).ok();
        tab2.add_string("IZIIZI", false).ok();
        tab2.add_string("IXIIXI", false).ok();
        tab2.add_string("IIZZIZ", false).ok();
        tab2.add_string("IIXIIX", false).ok();
        let mut tab3 = SymplecticTableau::new(6);
        tab3.add_string("ZIIZII", false).ok();
        tab3.add_string("XIIXXI", false).ok();
        tab3.add_string("IZIZZI", false).ok();
        tab3.add_string("IXIIXX", false).ok();
        tab3.add_string("IIZZZZ", false).ok();
        tab3.add_string("IIXIIX", false).ok();
        let mut tab4 = SymplecticTableau::new(6);
        tab4.add_string("ZIIZII", false).ok();
        tab4.add_string("XIIXII", false).ok();
        tab4.add_string("IZIIZI", false).ok();
        tab4.add_string("IXIIXI", false).ok();
        tab4.add_string("IIZIIZ", false).ok();
        tab4.add_string("IIXIIX", false).ok();
        let mut cm_12 = SymplecticTableau::controlled_meet(&tab1, &tab2);
        let mut cm_34 = SymplecticTableau::controlled_meet(&tab3, &tab4);
        if cm_12.tab.nb_qubits <= cm_34.tab.nb_qubits {
            cm_12
                .tab
                .add_qubits(cm_34.tab.nb_qubits - cm_12.tab.nb_qubits);
        } else {
            cm_34
                .tab
                .add_qubits(cm_12.tab.nb_qubits - cm_34.tab.nb_qubits);
        }
        let cm_1234 = SymplecticTableau::controlled_meet(&cm_12.tab, &cm_34.tab);
        let mut cm_1 = cm_1234.tab.clone();
        cm_1.post_select_1qs(&cm_1234.l_post_selects);
        cm_1.post_select_1qs(&cm_12.l_post_selects);
        cm_1.echelon(&cm_1.all_columns());
        tab1.echelon(&tab1.all_columns());
        assert_eq!(cm_1.nb_stabs, tab1.nb_stabs);
        tab1.add_qubits(cm_1.nb_qubits - tab1.nb_qubits);
        for i in 0..tab1.nb_stabs {
            assert_eq!(tab1.stab_as_string(i), cm_1.stab_as_string(i));
        }
        let mut cm_2 = cm_1234.tab.clone();
        cm_2.post_select_1qs(&cm_1234.l_post_selects);
        cm_2.post_select_1qs(&cm_12.r_post_selects);
        cm_2.echelon(&cm_2.all_columns());
        tab2.echelon(&tab2.all_columns());
        assert_eq!(cm_2.nb_stabs, tab2.nb_stabs);
        tab2.add_qubits(cm_2.nb_qubits - tab2.nb_qubits);
        for i in 0..tab2.nb_stabs {
            assert_eq!(tab2.stab_as_string(i), cm_2.stab_as_string(i));
        }
        let mut cm_3 = cm_1234.tab.clone();
        cm_3.post_select_1qs(&cm_1234.r_post_selects);
        cm_3.post_select_1qs(&cm_34.l_post_selects);
        cm_3.echelon(&cm_3.all_columns());
        tab3.echelon(&tab3.all_columns());
        assert_eq!(cm_3.nb_stabs, tab3.nb_stabs);
        tab3.add_qubits(cm_3.nb_qubits - tab3.nb_qubits);
        for i in 0..tab3.nb_stabs {
            assert_eq!(tab3.stab_as_string(i), cm_3.stab_as_string(i));
        }
        let mut cm_4 = cm_1234.tab.clone();
        cm_4.post_select_1qs(&cm_1234.r_post_selects);
        cm_4.post_select_1qs(&cm_34.r_post_selects);
        cm_4.echelon(&cm_4.all_columns());
        tab4.echelon(&tab4.all_columns());
        assert_eq!(cm_4.nb_stabs, tab4.nb_stabs);
        tab4.add_qubits(cm_4.nb_qubits - tab4.nb_qubits);
        for i in 0..tab4.nb_stabs {
            assert_eq!(tab4.stab_as_string(i), cm_4.stab_as_string(i));
        }
    }
}
